// <auto-generated />
using System;
using CmsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CmsApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709051758_AddPincodeDirectory")]
    partial class AddPincodeDirectory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CmsApi.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("CmsApi.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("CmsApi.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("GstAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("GstRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int?>("PaymentModeId")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SubtotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("PatientId");

                    b.HasIndex("PaymentModeId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("CmsApi.Models.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("CmsApi.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int?>("BloodGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GenderId")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pincode")
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BloodGroupId");

                    b.HasIndex("GenderId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("CmsApi.Models.PincodeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Pincode")
                        .IsUnique();

                    b.ToTable("PincodeDirectory");
                });

            modelBuilder.Entity("CmsApi.Models.StaticType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StaticTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "GENDER",
                            Description = "Patient Gender"
                        },
                        new
                        {
                            Id = 2,
                            Code = "BLOOD_GROUP",
                            Description = "Blood Group"
                        },
                        new
                        {
                            Id = 3,
                            Code = "APPOINTMENT_STATUS",
                            Description = "Appointment Status"
                        },
                        new
                        {
                            Id = 4,
                            Code = "INVOICE_STATUS",
                            Description = "Invoice Status"
                        },
                        new
                        {
                            Id = 5,
                            Code = "PAYMENT_MODE",
                            Description = "Payment Mode"
                        });
                });

            modelBuilder.Entity("CmsApi.Models.StaticValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("StaticTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StaticTypeId");

                    b.ToTable("StaticValues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "MALE",
                            DisplayValue = "Male",
                            IsActive = true,
                            SortOrder = 1,
                            StaticTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "FEMALE",
                            DisplayValue = "Female",
                            IsActive = true,
                            SortOrder = 2,
                            StaticTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "OTHER",
                            DisplayValue = "Other",
                            IsActive = true,
                            SortOrder = 3,
                            StaticTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Code = "A_PLUS",
                            DisplayValue = "A+",
                            IsActive = true,
                            SortOrder = 1,
                            StaticTypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Code = "A_MINUS",
                            DisplayValue = "A-",
                            IsActive = true,
                            SortOrder = 2,
                            StaticTypeId = 2
                        },
                        new
                        {
                            Id = 6,
                            Code = "B_PLUS",
                            DisplayValue = "B+",
                            IsActive = true,
                            SortOrder = 3,
                            StaticTypeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Code = "B_MINUS",
                            DisplayValue = "B-",
                            IsActive = true,
                            SortOrder = 4,
                            StaticTypeId = 2
                        },
                        new
                        {
                            Id = 8,
                            Code = "AB_PLUS",
                            DisplayValue = "AB+",
                            IsActive = true,
                            SortOrder = 5,
                            StaticTypeId = 2
                        },
                        new
                        {
                            Id = 9,
                            Code = "AB_MINUS",
                            DisplayValue = "AB-",
                            IsActive = true,
                            SortOrder = 6,
                            StaticTypeId = 2
                        },
                        new
                        {
                            Id = 10,
                            Code = "O_PLUS",
                            DisplayValue = "O+",
                            IsActive = true,
                            SortOrder = 7,
                            StaticTypeId = 2
                        },
                        new
                        {
                            Id = 11,
                            Code = "O_MINUS",
                            DisplayValue = "O-",
                            IsActive = true,
                            SortOrder = 8,
                            StaticTypeId = 2
                        },
                        new
                        {
                            Id = 12,
                            Code = "SCHEDULED",
                            DisplayValue = "Scheduled",
                            IsActive = true,
                            SortOrder = 1,
                            StaticTypeId = 3
                        },
                        new
                        {
                            Id = 13,
                            Code = "COMPLETED",
                            DisplayValue = "Completed",
                            IsActive = true,
                            SortOrder = 2,
                            StaticTypeId = 3
                        },
                        new
                        {
                            Id = 14,
                            Code = "CANCELLED",
                            DisplayValue = "Cancelled",
                            IsActive = true,
                            SortOrder = 3,
                            StaticTypeId = 3
                        },
                        new
                        {
                            Id = 15,
                            Code = "NO_SHOW",
                            DisplayValue = "No Show",
                            IsActive = true,
                            SortOrder = 4,
                            StaticTypeId = 3
                        },
                        new
                        {
                            Id = 16,
                            Code = "PENDING",
                            DisplayValue = "Pending",
                            IsActive = true,
                            SortOrder = 1,
                            StaticTypeId = 4
                        },
                        new
                        {
                            Id = 17,
                            Code = "PAID",
                            DisplayValue = "Paid",
                            IsActive = true,
                            SortOrder = 2,
                            StaticTypeId = 4
                        },
                        new
                        {
                            Id = 18,
                            Code = "CANCELLED",
                            DisplayValue = "Cancelled",
                            IsActive = true,
                            SortOrder = 3,
                            StaticTypeId = 4
                        },
                        new
                        {
                            Id = 19,
                            Code = "CASH",
                            DisplayValue = "Cash",
                            IsActive = true,
                            SortOrder = 1,
                            StaticTypeId = 5
                        },
                        new
                        {
                            Id = 20,
                            Code = "UPI",
                            DisplayValue = "UPI",
                            IsActive = true,
                            SortOrder = 2,
                            StaticTypeId = 5
                        },
                        new
                        {
                            Id = 21,
                            Code = "CARD",
                            DisplayValue = "Card",
                            IsActive = true,
                            SortOrder = 3,
                            StaticTypeId = 5
                        },
                        new
                        {
                            Id = 22,
                            Code = "NET_BANKING",
                            DisplayValue = "Net Banking",
                            IsActive = true,
                            SortOrder = 4,
                            StaticTypeId = 5
                        },
                        new
                        {
                            Id = 23,
                            Code = "INSURANCE",
                            DisplayValue = "Insurance",
                            IsActive = true,
                            SortOrder = 5,
                            StaticTypeId = 5
                        });
                });

            modelBuilder.Entity("CmsApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CmsApi.Models.Vitals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("BloodPressureDiastolic")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<decimal?>("BloodPressureSystolic")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal?>("OxygenSaturation")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("PulseRate")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Temperature")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("Vitals");
                });

            modelBuilder.Entity("CmsApi.Models.Appointment", b =>
                {
                    b.HasOne("CmsApi.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CmsApi.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CmsApi.Models.StaticValue", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("CmsApi.Models.Invoice", b =>
                {
                    b.HasOne("CmsApi.Models.Appointment", "Appointment")
                        .WithOne("Invoice")
                        .HasForeignKey("CmsApi.Models.Invoice", "AppointmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CmsApi.Models.Patient", "Patient")
                        .WithMany("Invoices")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CmsApi.Models.StaticValue", "PaymentMode")
                        .WithMany()
                        .HasForeignKey("PaymentModeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CmsApi.Models.StaticValue", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Patient");

                    b.Navigation("PaymentMode");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("CmsApi.Models.InvoiceItem", b =>
                {
                    b.HasOne("CmsApi.Models.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("CmsApi.Models.Patient", b =>
                {
                    b.HasOne("CmsApi.Models.StaticValue", "BloodGroup")
                        .WithMany()
                        .HasForeignKey("BloodGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CmsApi.Models.StaticValue", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BloodGroup");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("CmsApi.Models.StaticValue", b =>
                {
                    b.HasOne("CmsApi.Models.StaticType", "StaticType")
                        .WithMany("Values")
                        .HasForeignKey("StaticTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaticType");
                });

            modelBuilder.Entity("CmsApi.Models.Vitals", b =>
                {
                    b.HasOne("CmsApi.Models.Appointment", "Appointment")
                        .WithOne("Vitals")
                        .HasForeignKey("CmsApi.Models.Vitals", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("CmsApi.Models.Appointment", b =>
                {
                    b.Navigation("Invoice");

                    b.Navigation("Vitals");
                });

            modelBuilder.Entity("CmsApi.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("CmsApi.Models.Invoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CmsApi.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("CmsApi.Models.StaticType", b =>
                {
                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
